version: '3'

volumes:
  pg_data:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  notes_api:
    image: asseylumva/notes_api
    ports:
      - '8000:8000'
    env_file: .env
    depends_on:
      db:
        condition: service_healthy